reorder headers
Fixes the OS/2 build:

wcl386 -zq -bt=os2v2 -l=os2v2 -I"../huskylib" -fo=tdelay.obj -c ../src/tdelay.c
/opt/watcom/h/os2/tcpustd.h(59): Error! E1127: Type required in parameter list
/opt/watcom/h/os2/tcpustd.h(59): Error! E1022: Missing or misspelled data type near 'fd_set'
/opt/watcom/h/os2/tcpustd.h(59): Error! E1127: Type required in parameter list
/opt/watcom/h/os2/tcpustd.h(59): Error! E1022: Missing or misspelled data type near 'fd_set'
/opt/watcom/h/os2/tcpustd.h(59): Error! E1034: Symbol 'fd_set' already defined
/opt/watcom/h/os2/tcpustd.h(59): Error! E1127: Type required in parameter list
/opt/watcom/h/os2/tcpustd.h(59): Error! E1022: Missing or misspelled data type near 'fd_set'
/opt/watcom/h/os2/tcpustd.h(59): Error! E1034: Symbol 'fd_set' already defined
/opt/watcom/h/os2/tcpustd.h(59): Error! E1034: Symbol 'fd_set' already defined
Error: Compiler returned a bad status compiling '../src/tdelay.c'